### ISSUE TITLE
Remove this feed from OpenWrt's feeds.conf.default?

### ISSUE THREAD

**Issue by pmelange** [freifunk/openwrt-packages#37]
As a result of the disinterest in the community as shown in pr #34, and the overall lack of movement in this repo, I would suggest that this feed be removed from the main OpenWrt feed list.  

https://github.com/openwrt/openwrt/blob/17fa01bb79be12a08f8f7a0beb7f0d73618a6193/feeds.conf.default#L5

As it seems like the only project which uses this feed currently is freifunk-berlin, which has it's own make system and feeds list, I don't see this as a problem.  If I am mistaken and other projects are dependent on this feed, please comment below.

I would submit a PR with OpenWrt sometime at the beginning of March 2021.

**Comment by PolynomialDivision** [comment]
I think you should talk to @dangowrt since he picked the feed into 19.07 branch.

https://github.com/openwrt/openwrt/commit/2a3dbded93775aeaf28fbebbd6aada07c9f588c1#diff-2f18a0999ba128c305a9d3771d715b18b91556d8d0929ec74f9992348f994272

I would like to push all stuff to `luci` and `packages` feed (except all that uci default stuff).
I will rewrite all the apps in javascript, soon. If I do this I would prefer to push that in luci, since we will benefit from other more expeirenced luci devs, more feedback and treewirde luci changes.

**Comment by PolynomialDivision** [comment]
Another option is to reactivate this openwrt-packages, and mainatain the needed packages here. I think we are not enough to maintain our own packages-feed-build-infrastructure. For now @Akira25 maintains it, but what will happen if he will go?

**Comment by andibraeu** [comment]
weimarnetz also uses this package feed ;)

**Comment by lynxis** [comment]
Just in case if you want to remove it. I've no opinion if you should or not. It might be a good idea to do it before the release of openwrt 21.02 so it can be also removed from the release.

**Comment by PolynomialDivision** [comment]
http://lists.openwrt.org/pipermail/openwrt-devel/2021-February/033807.html

**Comment by pmelange** [comment]
> weimarnetz also uses this package feed ;)

They have their own build system and feeds.conf file.  They don't use openwrt's feeds.conf.
https://github.com/weimarnetz/firmware/blob/brauhaus-19.07/feeds.conf

**Comment by akira25** [comment]
> Another option is to reactivate this openwrt-packages, and mainatain the needed packages here. I think we are not enough to maintain our own packages-feed-build-infrastructure. For now @Akira25 maintains it, but what will happen if he will go?

We might have a discussion on  that later on (in another issue). At the moment, I'm in favour of dropping the packagefeed from openwrt:
* The Freifunk-Repo seems pretty inactive to me
* As far as I can tell, Gluon looks like it doesn't use this repo
* Freifunk Berlin have set up their own package feed, which might go (partly) upstream in the future (to be discussed for example [here](https://github.com/Freifunk-Spalter/packages/issues/45))
* Any Projects that are forks of the former berlin firmware (hedy), use their own feeds.conf files, so that they override the openwrt-feeds anyway.

IMO, we should modernise this and drop the package feed.

**Comment by pmelange** [comment]
Yes, freifunk-gluon creates their own feeds.conf file too

https://github.com/freifunk-gluon/gluon/blob/master/scripts/feeds.sh

**Comment by pmelange** [comment]
I have created two PR's to remove the feed from OpenWrt's master and openwrt-21.02 branches.

https://github.com/openwrt/openwrt/pull/3900
https://github.com/openwrt/openwrt/pull/3901

**Comment by pmelange** [comment]
PR https://github.com/openwrt/openwrt/pull/3901 has been closed so that the focus of the conversion happens in the PR for the master branch.

**Comment by pmelange** [comment]
https://github.com/openwrt/openwrt/commit/20caa68fec4fe033f72c9d488639f8dd2bcfa02c

https://github.com/openwrt/openwrt/commit/ff6b36b9548bbb869c2f5a5ffc0e415e25bc857e

These two commits have removed the repo from the default openwrt feeds.  Any projects which want to include it should add the feeds manually to their feeds.conf files.

**Comment by PolynomialDivision** [comment]
> a) it is an external project and the OpenWrt team does not have access to it.

Arrgh, don't put that into people's heads that freifunk is an external project. xP
